steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/ohagi-dinner-private/ohagi-dinner-private-api/ohagi-dinner-private-api', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-northeast1-docker.pkg.dev/ohagi-dinner-private/ohagi-dinner-private-api/ohagi-dinner-private-api']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'ohagi-dinner-private-api', '--image', 'asia-northeast1-docker.pkg.dev/ohagi-dinner-private/ohagi-dinner-private-api/ohagi-dinner-private-api:latest', '--region', 'asia-northeast1', '--execution-environment', 'gen2']
images:
- asia-northeast1-docker.pkg.dev/ohagi-dinner-private/ohagi-dinner-private-api/ohagi-dinner-private-api


